### ISSUE TITLE
FLUX support mentioned nowhere, why?

### ISSUE THREAD

**Issue by n0valis** [mcmonkeyprojects/sd-dynamic-thresholding#105]
I have seen that people are using sd-dynamic-thresholding for making FLUX negative prompts possible. I also use it to make flux prompting more variable.

Why is the support of FLUX not mentioned in the description?

**Comment by mcmonkey4eva** [comment]
The readme & wiki were written when SD1 and SD2 were the only model archs, long before SDXL, SD3, or Flux.

It supports other models implicitly despite never being coded for them, and turns out to be particularly useful on Flux (albeit I personally wouldn't use it that way, just cause Flux will take twice as long to run with negative prompting and it's already annoyingly slow compared to other models).

**Comment by mcmonkey4eva** [comment]
Swap your CFG to exactly 1 and compare that to any other CFG - it'll be about double for non-1 CFG, because it literally runs the model twice to calculate the negative prompt and apply CFG, whereas at CFG=1 it only has to run the model once.

**Comment by n0valis** [comment]
Ok, I see what you mean. I always thought that was related to the dyn-threshold node. But it isn't.
In fact I get the same result with cfg = 3 and dyn-threshold disabled. I thought Flux would ignore higher than 1 values anyway.
But that doesn't seem to be the case. It is the sampler probably

cfg = 3 : 9,1/it   
cfg = 1 : 5/it    

sd-dyn-threshold bypassed:
cfg = 3 : 8.3/it  
cfg = 1 : 5/it

**Comment by n0valis** [comment]
I have one last question: Using sd-dynamic-thresholding in Flux in conjunction with cfg, what can I expect to happen?
Aside from the negative prompt recognition, which effect can I expect  from a higher cfg value than 1 on the generated image and what effect could I expect from raising it to 3,4,5 and so forth? Is it better prompt following?
