### ISSUE TITLE
Very poor IMG2IMG outputs on latest version of SD.Next

### ISSUE THREAD

**Issue by a2ZxgdqHeSs8F51cIyuK** [mcmonkeyprojects/sd-dynamic-thresholding#83]
Hello,
issue has been documented over on SD.Next's repository: vladmandic/automatic#2457
Could you kindly take a look at it and see if you can solve it or help Vlad with it? 
If you need more information or want me to run some tests let me know.

**Comment by mcmonkey4eva** [comment]
`(Also contains a minor tweak to make the config options be visible by default).` those are hidden if you're using a scheduler that doesn't use them, and visible if you use a scheduler that does have them.

I'm not sure why you did the `- 2` change.

The `total_steps` part, uh, _shouldn't_ be needed in theory unless SDNext is doing something weird - but assuming perhaps it is, if your change worked it'd be from that part, so I've gone ahead and imported just that bit

**Comment by KerfuffleV2** [comment]
@mcmonkey4eva Sorry for the confusion and thanks for the reply, my post wasn't clear. I'm actually not using SDNext, just the devel branch of normal webUI. I was just asking the other person if my changes helped with their issue (since I thought it could possibly be related to the step count thing).

I don't _actually_ know what I'm doing, basically I added a bunch of debug output to the script and looked at the values. `- 2` there is what resulted in it hitting the scale I expected on the last step.

> those are hidden if you're using a scheduler that doesn't use them, and visible if you use a scheduler that does have them.

They got hidden every time the page reloaded for me and the only way to see them would be to toggle the script to disabled then back to enabled _and_ then go and change type to a different value and then back again (so the limits would show up).

Possibly it's related to using the dev version of webui rather than the main one. Anyway, you probably shouldn't make changes based on what I said unless you can verify it's actually correct. :) All I can really say is I get better results with those changes with my current set up.

**Comment by a2ZxgdqHeSs8F51cIyuK** [comment]
I haven't tested that yet, but if you look at the late replies on the issue I linked, it seems it was just an issue with two settings not showing up and since they defaulted to the minimum value they gave terrible results.
The two settings show up by fiddling a bit with other menus and once they're set to appropriate values the outputs are good again.

**Comment by mcmonkey4eva** [comment]
Wait, what do you mean "when the page reloaded" and all?
Auto webui doesn't persist params at all, so the fields are hidden again after a reload because they're no longer relevant (back to Constant)

**Comment by KerfuffleV2** [comment]
@mcmonkey4eva 

> Wait, what do you mean "when the page reloaded" and all? Auto webui doesn't persist params at all

It actually can, you can save the state as defaults: `Settings -> Other -> Defaults`. In that case, it'll load with dynamic thresholding enabled but you can't see the settings until you follow the process I described before: toggle it off then on again to be able see any configuration options and then change the the scaling types to something else then back again to actually see stuff like the minimums. That's a built in feature, not an addon as far as I know (pretty sure it's also not only in the devel branch).

**Comment by mcmonkey4eva** [comment]
Ehhh screw it I'm not up for a fight with gradio's broken software, I went ahead and just made all params always visible. Another bit of nicer-UI lost to gradio being too buggy to reliably have niceness :(
