### ISSUE TITLE
Question Regarding New Tools

### ISSUE THREAD

**Issue by TomLucidor** [mcmonkeyprojects/sd-dynamic-thresholding#93]
Characteristic Guidance claims that Dynamic Thresholding will cause greying out of images, are there things that can be done that prevent such issue? https://github.com/scraed/CharacteristicGuidanceWebUI
Note: there is another CFG scheduler https://github.com/guzuligo/CFG-Schedule-for-Automatic1111-SD
Note: averaging seems similar https://github.com/klimaleksus/stable-diffusion-webui-anti-burn

**Comment by mcmonkey4eva** [comment]
CFG scheduler is redundant as dynthresh includes that.
Antiburn is a separate concept that should be stackable alongside this extension in theory.
Characteristic Guidance is separate and interesting. I'm gonna have to look into that more.
DynThresh only causes graying out if you get the parameters wrong. It does happen, but it's avoidable if you just tweak params.
If you're looking into the options here, *Self Attention Guidance* also looks really interesting. It *reduces* the available parameters to fiddle rather than adding more as all the above do, but instead uses smart automation to select good values dynamically as it goes.
